#!/bin/bash

PSQL_IP=$DB_PORT_5432_TCP_ADDR
PSQL_PORT=$DB_PORT_5432_TCP_PORT

echo "
CREATE ROLE $APP_USER WITH LOGIN PASSWORD '$APP_PASS' VALID UNTIL 'infinity';
CREATE DATABASE $APP_DB WITH ENCODING 'UNICODE' TEMPLATE=template0;" \
| PGPASSWORD="$DB_PASS" psql -h $PSQL_IP -p $PSQL_PORT -d postgres -U $DB_USER -w
